### ISSUE TITLE
Websocket + web

### ISSUE THREAD

**Issue by grunk** [bel2125/civetweb#101]
Hello,

i'm using civetweb embedded in a C++ app to serve web page (443 & 80).
I need to add websocket support to some pages.

Should i start a second instance of civetweb with differents ports and callbacks to handle the websocket ?

Something like that : 

```
const char * options[] = {
	"document_root", DOCUMENT_ROOT, 
	"listening_ports", PORT, 
	"ssl_certificate", SSL_CERTIFICATE, 
	"error_log_file", LOG_FILE,
	"enable_directory_listing","no",
	"extra_mime_types",".crt=application/x-x509-ca-cert",
	0
};
this->m_pServer = new CivetServer(options);

const char * options2[] = {
	"document_root", DOCUMENT_ROOT, 
	"listening_ports", "40000", 
	0
};
this->m_pServer2 = new CivetServer(options2,callbacks);
```

Or is it possible to change the websocket port ?

Thanks

**Comment by bel2125** [comment]
You can use the same instance for both.
You can even use the same port for http and websocket, they use a different namespace anyway.
I would actually even recommend to use the same port, as some webbrowsers/filters/security settings don't like if you have a http connection to one server that opens a ws connection to another one.

**Comment by bel2125** [comment]
Did you have a look at my websocket example:
https://github.com/bel2125/civetweb/blob/master/test/websocket.xhtml#L53
For http://xyz.com/whatever (port 80) you can open ws://xyz.com/whatever (port 80), 
and for https://xyz.com/whatever (port 443) you can open wss://xyz.com/whatever (port 443).
http:// https:// use a different namespace than ws:// wss://
You can even set a different document root for both protocols (which would be only useful if you handle WebSockets in Lua). For a callback in C++ the document root is not that important anyway.

**Comment by bel2125** [comment]
By the way, I plan to add some uri specific callbacks soon (see #30 - I know it's old, I had some more urgent things to do, but it is not a bad idea and should be done).
This would make it even easier to use the same instance and the same port for ws and http.

Or do you have any reason why you want http and ws to use different ports?

**Comment by grunk** [comment]
Thanks for you answers :)
I was wondering if a second instance is needed because we can get civetweb working with websocket and specific handler for the web.

We can have websocket working and displaying document root with an http request by using this code : 
https://gist.github.com/grunk/59258ce5cc560b743801

But we also need custom handlers for the web parts. So we used CivetServer to init civetweb : 
https://gist.github.com/grunk/cc9c08d6b4bbeb50233a

This last snippet crash in WebSockCallbacks # eventMain : 

```
static void * eventMain(void * arg) {
    char msg[256];
    struct mg_context *ctx = (struct mg_context *)arg;
    tWebSockContext *ws_ctx = (tWebSockContext*) mg_get_user_data(ctx);

    ==> ws_ctx->runLoop = 1; // ws_ctx is NULL
    while (ws_ctx->runLoop) {
        time_t t = time(0);
        struct tm * timestr = localtime(&t);
        sprintf(msg,"title %s",asctime(timestr));

        send_to_all_websockets(ctx, msg, strlen(msg));

        mg_sleep(1000);
    }
```
We are probably missing something but we can't find what :(
Is it possible to use CivetServer to achieve our goal ?

PS : uri specific callbacks for websocket is a good news :)

**Comment by bel2125** [comment]
> Is it possible to use CivetServer to achieve our goal (websocket + document root + custom handler) ?

Definitely yes. I'm using it the same way - beside that I use the C API (civetweb.h) directly, the C++ class is just a wrapper around this C API anyway.

**Comment by bel2125** [comment]
The function to register URI specific websocket callbacks (as discussed in #30) is now available: `mg_set_websocket_handler`.


An example how you can do exactly what you describe (one instance for serving files with http, http callbacks and websocket callbacks) can be found here:
https://github.com/bel2125/civetweb/blob/master/examples/embedded_c/embedded_c.c

Please have a look, and tell me if you miss something or something is unclear.
