### ISSUE TITLE
Compiler warning (error with -Werror) in send_file_data 

### ISSUE THREAD

**Issue by deltaluca** [bel2125/civetweb#103]
gcc 4.9.2 from ubuntu repositories.

```
In function ‘__fread_alias’,
    inlined from ‘send_file_data’ at ../external/civetweb/civetweb.cc:4230:76:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:290:66: error: call to ‘__fread_chk_warn’ declared with attribute warning: fread called with bigger size * nmemb than length of destination buffer [-Werror]
  return __fread_chk (__ptr, __bos0 (__ptr), __size, __n, __stream);
```

As far as I can see, this warning is spurious as the read length is 'always' less than sizeof(buf) in the code... scan-build doesn't suggest anything, and changing to_read to be size_t incase it was compiler thinking it might be negative integer didn't help either.

As it stands, I really don't want to have to turn off -Werror, so am adding in some pragmas to temporarigly disable that warning around the code.

**Comment by bel2125** [comment]
Your file is civetweb.cc is this the civetweb.c file any you mean this line:
https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L4230

Then I don't really see the reason for a warning, since the buffer size is checked, and it is also not possible to call with a negative value.

**Comment by deltaluca** [comment]
Yes, it's the civetweb.c. And yes, I agree the warning is spurious, I was curious to see if you had any ideas on convincing the compiler this is the case

**Comment by bel2125** [comment]
I don't get this warning with "make" and "make WITH_LUA=1"
I used gcc 4.9.1 on Ubuntu

What make command are you using?

**Comment by bel2125** [comment]
This seems to be a bug in gcc:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=751812

So there is nothing we can do here.
