### ISSUE TITLE
Unused functions base64_decode, b64reverse.

### ISSUE THREAD

**Issue by deltaluca** [bel2125/civetweb#104]
I like to compile with warnings as errors and as many warnings turned on as possible :) It likes to tell me off for unused functions (like these two)

**Comment by bel2125** [comment]
base64_decode is called when you compile with Lua support, and b64reverse is called by base64_decode:
https://github.com/bel2125/civetweb/blob/master/src/mod_lua.inl#L666

Your linker will eliminate unused functions if you do not compile WITH_LUA

**Comment by kainjow** [comment]
Maybe surround it with #ifdef WITH_LUA ?

**Comment by bel2125** [comment]
Yes, this would eliminate the warning if you build an EXE without Lua. In the moment it happens to be that it is not needed when you compile with websocket but without Lua.

But honestly, do you think a system built with like 10 different compilers and operating systems, dozens of WITH_SOMETHING combinations and multiple contributors should compile in all these hundreds of combinations warning free without hundreds of #ifdefs that would finally make the code unmaintainable?
An unused function is probably one of the lowest priority warnings.

**Comment by bel2125** [comment]
Now the following commands compile without warning on gcc 4.9.1 on Ubuntu Linux 14.10

    make
    make WITH_WEBSOCKET=1
    make WITH_IPV6=1
    make WITH_WEBSOCKET=1 WITH_IPV6=1

WITH_LUA=1 gives a few warnings from third party components (Lua, sqlite) that I will definitely NOT fix - this has to be done by the programmers of the third party modules.

I can not guarantee for any other compiler, any other operating system including different Linux distribution, not even different versions of gcc or different Ubuntu versions.

**Comment by bel2125** [comment]
These two warnings do no longer occur.
In general, I will have a look at all remaining warnings, once the build system with cmake (#94) is ready.
