### ISSUE TITLE
lua_preload_file example

### ISSUE THREAD

**Issue by alisabri** [bel2125/civetweb#110]
Hi,
Thanks for your time and efforts for civetweb.

Is there any example regarding usage of "lua_preload_file" ? 
Could it be possible to define global Lua callback functions for websocket in this file ?

Regards,
Ali

**Comment by nihildeb** [comment]
there isn't an example, but the way I learned about the feature is the test.

if you set the preload option with this file:
https://github.com/bel2125/civetweb/blob/master/test/lua_preload_file.lua

and then put this file in your docroot and open it in the browser:
https://github.com/bel2125/civetweb/blob/master/test/page2.lp

you should see how it works. in the preload file, just add stuff to the mg table, and then it will be available to all your scripts via the exposed mg api.

**Comment by alisabri** [comment]
Thanks a lot

I will try that

**Comment by bel2125** [comment]
nihildeb is absolutely correct.
See also my answer to the same question on the mailing list I wrote before reading this here:
https://groups.google.com/forum/#!topic/civetweb/m9tLa_0nU3c

Can actually add everything you want to every table you want, not only to the mg table.
You can also use it to ensure backward compatibility of the Lua API if some obsolete functions are replaced by newer ones, so you don't need to touch all script files in a larger web project.

**Comment by alisabri** [comment]
Thanks for quick reply.

I am trying.

Regards
