### ISSUE TITLE
-DUSE_WEBSOCKET

### ISSUE THREAD

**Issue by softwarenerd** [bel2125/civetweb#114]
Hi,

I'm seeing some compile warnings with USE_WEBSOCKET:

civetweb.c: In function 'handle_request':
civetweb.c:6787:34: warning: passing argument 5 of 'handle_websocket_request' from incompatible pointer type [enabled by default]
civetweb.c:6017:13: note: expected 'mg_websocket_ready_handler' but argument is of type 'void (*)(const struct mg_connection *, void *)'
civetweb.c:6787:34: warning: passing argument 6 of 'handle_websocket_request' from incompatible pointer type [enabled by default]
civetweb.c:6017:13: note: expected 'mg_websocket_data_handler' but argument is of type 'int (*)(const struct mg_connection *, int,  char *, size_t,  void *)'
civetweb.c: At top level:

Just wondering.

I'm using the library, and hope to contribute to it, once I get some more things working on my end.

Thanks!
Brian

**Comment by bel2125** [comment]
Recently I changed some `const struct mg_connection *`  <--> `struct mg_connection *` (see #109), so maybe there is a `const` warning left.
I don`t see this warning myself: Which compiler and operating system are you using?

**Comment by bel2125** [comment]
Please try it again with your compiler.

**Comment by softwarenerd** [comment]
OK, will do. Was out with a cold yesterday. Will try now. Thanks!

**Comment by bel2125** [comment]
I hope that I finally managed to clean up all 'const' vs *not const* issues.
If you still see some, please tell me - otherwise I will close the issue in a few days.

**Comment by bel2125** [comment]
I think the fixes from three weeks seemed to solve all remaining `const` problems.
