### ISSUE TITLE
Matching of URLs 

### ISSUE THREAD

**Issue by bms20** [bel2125/civetweb#116]
Not sure if this has been covered before, but:

Running example.cpp I find that going to:
http://localhost:8081/a
returns the A api method (as expected).  However, going to /a/blah also goes to the a handler.

This looks like a pattern match failure to me - is there something I misunderstand here?

**Comment by bel2125** [comment]
The exact match /a/b opens the ABHandler.
Exact matches are preferred over partial matches.
Both /a/b and /a are only partial matches for /a/blah - within partial matches, the one registered earlier is preferred.

**Comment by bms20** [comment]
So is there an option to disable all partial matches?

**Comment by bel2125** [comment]
You could use patterns:
Add a $ at the end of each path - but you really need to do this with each path then, if you forget one it will still do partial matches with it.

**Comment by bel2125** [comment]
I added a little example.

**Comment by bms20** [comment]
Awesome - thank you very much!

I've put civetweb to good use in the meantime!

     -Brett
