### ISSUE TITLE
Trailing / bypassing password authentication

### ISSUE THREAD

**Issue by ccahiggins** [bel2125/civetweb#120]
I am using the global_auth_file option on an embedded server. If I browse to a page and add / at the end the page shows without asking for a password, eg. http://localhost/example/

If I remove the last / I get the password dialog.

**Comment by bel2125** [comment]
I can not reproduce this.

What version are you using, and what operating system?

**Comment by ccahiggins** [comment]
Just realised I'm using 1.6 from sunsetbrew. I'll try it from here and see if it works.

**Comment by bel2125** [comment]
Please tell me if it works, and if not what operating system and version you are using.

**Comment by ccahiggins** [comment]
I'm not sure what the problem was but I have got it working using the source from here now. Thanks

**Comment by bel2125** [comment]
Problem does not exist in this branch -> issue closed
See also https://groups.google.com/forum/#!topic/civetweb/VyOBjI67R-Q
