### ISSUE TITLE
Compilation Error in  src\mod_lua.inl(19): error C2275

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#132]
Compiled using `VS2010`,  error info:

<pre>
civetweb-master\src\mod_lua.inl(19): error C2275: “HANDLE”: 将此类型用作表达式非法( something like `Invalid expression`)
</pre>
 
caused by line 19 ~21
(void)addr;
	(void)prot;
	(void)flags;
	(void)offset

When I remove those lines , it compiled successfully.

**Comment by bel2125** [comment]
Interesting.
The sole purpose of these lines was to avoid "unused parameter" warnings.

**Comment by kainjow** [comment]
Ah, it's because MSVC is only C89, so variables have to be defined before statements.

**Comment by shawnye** [comment]
Compilation passed ,thank you!
