### ISSUE TITLE
can not find `boundary` when post to test/handle_form.lua 

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#137]
-- Get the boundary string.
bs = "--" .. ((mg.request_info.content_type):upper():match("BOUNDARY=(.*)")); -- line 40
cause `bs` to be capital letters, `bdata` can not find matched `bs`.

I change the line to :
bs = "--" .. ((mg.request_info.content_type):match("boundary=(.*)"));

It run without error (Chrome browser)

**Comment by bel2125** [comment]
I applied this patch. Thanks.
