### ISSUE TITLE
mg.send_file(filename)  `downloaded file name` issue

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#144]
When using  `mg.send_file(filename) `    -- send a file, including MIME type

there seems two problems:
1. can not custom filename for downloader ，it is of no use setting `Content-Disposition: attachment; filename=custom_filename.zip` in http header.
  Could you add a paramter  like  `mg.send_file(filename, download_filename)` to support this feature?
2. even though, it can not get the `filename` parameter for downloader, for example:

http://localhost:8180/lua/download.lua?filename=abc,txt
the downloader get filename `download.lua` instead of `abc.txt`

Is there any sugguestion?

**Comment by jeremywood** [comment]
I ran into this issue myself, and have added a couple of functions to
civetweb to work around it. I'm not sure if this is something that should
be in the library, but here's what I did:

I added a mg_send_file_download function, as well as
handle_file_request_download.

In my testing, these are the header entries that will most effectively
force a file download with a specified name:

                     "Content-Type: application/force-download\r\n"
                     "Content-Type: application/octet-stream\r\n"
                     "Content-Type: application/download\r\n"
                     "Content-Disposition: attachment;filename=%s\r\n"

**Comment by shawnye** [comment]
Thank you,

I change the source with the header you supplied, and change api:
mg.send_file(filename) ==&gt; mg.send_file(original_file_path, download_file_name)

It works
