### ISSUE TITLE
Is is possible for civetweb  to support ` debug mode`?

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#146]
it is very tedious to debug *.lua without `print` info, 
I have to write to *.log manually, or write to HTML page.

Is is possible for civetweb  to support ` debug mode`?
providing a terminal window and directly show  `print` info

**Comment by bel2125** [comment]
If you just want to store it in a file using the "print" function, add a `lua_preload_file` which defines `print` as a function writing to any file you want. This works out of the box without any changes to the source code.

It is even possible to do single step debugging in Lua.
Lua does have interfaces to write such a debugger: http://lua-users.org/wiki/DebuggingLuaCode
