### ISSUE TITLE
Embedded_c.c example: ws connection drops after a few seconds

### ISSUE THREAD

**Issue by everte** [bel2125/civetweb#148]
I'm trying to convert from mongoose to civetweb (more community driven and due to the license). I'm using it mainly as a websocket server and there are a few differences between mongoose and civetweb so I was trying to learn by using the (what seems, most updated) example to build on and see what changes my code will need.

I'm using the embedded_c.c example (git master pull from yesterday) on linux 64 bit with gcc 4.9.2. The webbrowser is able to connect with websocket, receives the greeting message and it will show the timer from the 'informWebsockets' function. But after a few seconds (3-10) the connection drops (and the WebSocketCloseHandler() function is being used).

The options array contains "websocket_timeout_ms" with the value from the example ("3600000"). Is there something missing in the example what should be done to keep the connection alive?

**Comment by bel2125** [comment]
This seems to be a bug, that has been introduced recently by a bug fix for a different issue.
I will have a look tomorrow.

**Comment by everte** [comment]
Thanks for quickly resolving this issue! In both the example (embedded_c.c) and my own code this seems to be working fine :).

**Comment by bel2125** [comment]
Fixed.
