### ISSUE TITLE
Civitweb can't serve from RAMDisk

### ISSUE THREAD

**Issue by RPGillespie6** [bel2125/civetweb#152]
If civetweb is running in an embedded linux environment, it seems as though it doesn't recognize ramdisk files and directories -- it always returns 404 from civetweb.c:8038:
			`send_http_error(conn, 404, "%s", "Not found");`

I also get the following console error:

`scan_directory: mg_stat(/path/in/ramdisk) failed: No such file or directory`

Civetweb itself is running from the ramdisk. It works if I try to access somewhere on a physical drive (flash, etc.) but if I try to access a virtual drive it always returns error 404.

https://en.wikipedia.org/wiki/RAM_drive

I know this is an issue because if I do the same thing with mongoose then it just works -- so the way civetweb is detecting files and folders might not be robust enough.

How does civetweb determine if the uri is a valid directory or file? If you can point me to the area of code responsible for this, I can help debug...

**Comment by bel2125** [comment]
I just checked it again with a tmpfs ramdisk, without any problems.
This is what I did:

    mkdir /mnt/ramdisk
    mount -t tmpfs -o size=512m tmpfs /mnt/ramdisk
    cp -r test /mnt/ramdisk
    ./civetweb -document_root /mnt/ramdisk/test
==> everything works well

What kind of ramdisk are you using: tmpfs, ramfs, something else?
What kind of "embedded Linux" are you using: Something based on a major distribution (like a minimal/small Debian image) or your own Linux from scratch?

**Comment by RPGillespie6** [comment]
I am using [MontaVista Linux 6](https://en.wikipedia.org/wiki/MontaVista#MontaVista_Linux), and I believe we are using [cramfs](https://en.wikipedia.org/wiki/Cramfs) for the filesystem of the ramdisk. I will double check on Monday and see if I can replicate it on a non-embedded platform so I can give you a more precise way to debug.

**Comment by bel2125** [comment]
I can use cramfs in Ubuntu X86 as well. I made the following test:

    /path/to/civetweb/test$ mkcramfs . /tmp/cramfs.image
    $ sudo mount -t cramfs -o loop /tmp/cramfs.image /mnt/cramdisk
    $ ../civetweb -document_root /mnt/cramdisk/

The ramdisk is created, but http://localhost:8080/<anything> always shows:

    Error 404: Not Found
    Not found

This is probably what you see as well. Strangly, all files seem to be created `1970-01-01 01:00:00.000000000 +0100` - probably exactly UNIX time 0.
In CivetWeb, there is a some old code that checks the `modification_time` member of an internal file structure for `!= 0`.

I don't know if there is an easy way to tell cramfs a modification date. If you know one, this would be a quick check. But I anyway want to change this code - checking for `modification_time == 0` is not a proper criterion for non-existence.

**Comment by bel2125** [comment]
It seems like the problem was really the date in my test. Now CivetWeb also works for files modified `1970-01-01 00:00:00` (UNIX time 0). 
Please check if this works for you now as well.

**Comment by RPGillespie6** [comment]
I checked and that fix seems to have worked. Thanks for the fast support - you can close this issue.
