### ISSUE TITLE
user_data not set when mg_start() is called

### ISSUE THREAD

**Issue by linev** [bel2125/civetweb#153]
Typical situation - second server with same HTTP address is started.
Civetweb delivers message "cannot bind to 8080: 98 (Address already in use)"
But mg_get_request_info(conn)->user_data returns 0.
And I use user_data for object pointer, which should process requests and related errors.
Could one implement such feature?

**Comment by bel2125** [comment]
Sorry, I did not really got the point.

You start two civetweb instances with the same port? 
Or you embed it in another application and start two instances of this application?
If the address is already in use, the server does not really start, and you need to start with a different port?
Now, is the problem to find out why the server did not start correctly?

mg_get_request_info returns 0 for what conn object?
What callback?

What system? Windows/Linux?
What civetweb version?

**Comment by linev** [comment]
I embed citeweb in another application and start two instances of this application.
And for the second instance of the application I want to know why server not started correctly,
looking in message text in *log_message* handler. My handler looks like:

   static int log_message_handler(const struct mg_connection *conn, const char *message)
   {
      return TCivetweb::ProcessLogMessage(mg_get_request_info((struct mg_connection *)conn)->user_data, message);
   }

And in this situation *user_data* is 0 which should be pointer on my object.

I using both Linux and Windows. Currently Civetweb version 1.6 is used, 
but I also test civetweb from repository.

**Comment by bel2125** [comment]
I think I am doing exactly what you want in the `main.c` file in the current CivetWeb source code.

Here I pass a pointer to an user data object:
https://github.com/bel2125/civetweb/blob/master/src/main.c#L794

And here I access the user data object in a log_message callback. In this case I store the first error message in this user data object, to display it later in a message box.
https://github.com/bel2125/civetweb/blob/master/src/main.c#L556

If I start two instances of CivetWeb using the same port, the second displays an error message box on Windows:

    Error:  |
    -----------
    -----------------------------------------------------------------------
    Failed to start Civetweb:                                             |
    cannot bind to 8080: 10048 (Bad file descriptor)                      |
    -----------------------------------------------------------------------

The code for this is here:
https://github.com/bel2125/civetweb/blob/master/src/main.c#L800

I did not check what V1.6 did exactly, but for me this works in the current version.

**Comment by linev** [comment]
Now I see a difference.
Civetweb 1.6 does not have function mg_get_context(conn) and mg_get_user_data(ctx).
Therefore I tried to get user_data from associated request, which was not valid in this particular case. 
When taking user_data from context pointer, everything works.
I patch my 1.6 version and will wait for next civetweb release.
