### ISSUE TITLE
After mg.send_file(dir_path), the link in page is incorrect

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#157]
docs.lua:
<pre>
local fn = mg.get_var(mg.request_info.query_string, "filename");
local base_dir = lfs.currentdir() .. '/docs/'
if fn then
	path = path .. fn
end	
mg.send_file(path)
</pre>

I use `http://localhost:8080/docs.lua?filename=`
that's ok except that the link in the page:

http://localhost:8080/docs.luaABC.doc

note: filename `ABC.doc` is append directly to the uri
Should I use url rewrite to handle this problem?

thank you

**Comment by bel2125** [comment]
I'm not exactly sure what you want to do, but maybe this example already shows you what you need:

https://github.com/bel2125/civetweb/blob/master/test/page3.lua

**Comment by shawnye** [comment]
I found difference :
My example: The file-list page is created automatically by civetweb itself. 
Your example: the file-list page is created manually by your code.
