### ISSUE TITLE
Unable to seek in file on Windows..

### ISSUE THREAD

**Issue by xtne6f** [bel2125/civetweb#158]
from commit c762a77c0ec6da41a9b1d5e6b2cc275be1561fa1. The result of `_lseeki64()` have to be compared with exactly `-1`.

**Comment by bel2125** [comment]
You mean these lines:

 		if (offset > 0 && fseeko(filep->fp, offset, SEEK_SET) != 0) {
 			mg_cry(conn, "%s: fseeko() failed: %s", __func__, strerror(ERRNO));

Linux will return -1 on error and 0 on OK:
http://man7.org/linux/man-pages/man3/ftello.3.html#RETURN_VALUE

Windows uses the definition `#define fseeko(x, y, z) (_lseeki64(_fileno(x), (y), (z)))`, so it will return -1 on error and the absolute offset on ok:
https://msdn.microsoft.com/en-us/library/1yee101t.aspx

I think commit c762a77 makes no difference - it works for Linux before and after this commit, and it does not work for Windows before and after this commit, right? So it must be fixed for Windows anyway.

**Comment by xtne6f** [comment]
Right. Before commit c762a77c0ec6da41a9b1d5e6b2cc275be1561fa1, the returned value was ignored and continued following `while (len > 0) { ...`, but after is not.

**Comment by bel2125** [comment]
Before https://github.com/bel2125/civetweb/commit/c762a77c0ec6da41a9b1d5e6b2cc275be1561fa1 it was possible that civetweb returns the wrong part of the file. This needs to be fixed too.

**Comment by xtne6f** [comment]
Thank you very much! Download files are seekable now with 7e1775ff1c622a308672786aae757da952e85947. (tested on VC++2010)
