### ISSUE TITLE
handle_form.lua upload file append '\n' for each row?

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#171]
when test/handle_form.lua upload utf8 encoding list,

the uploaded file is appended '\n' for each row ,as below:
<pre>

------WebKitFormBoundaryRBxwg6CAW5fWlClh

Content-Disposition: form-data; name="upload"; filename="list_utf8.txt"

Content-Type: text/plain

13899401

13899410

13899419

13899393

</pre>

![hex](https://cloud.githubusercontent.com/assets/579997/8691487/ed09d7a2-2af5-11e5-9984-0563f87f5b5b.jpg)

The exceeded '\n' corrupt my file ,is there any suggestion? 
Thanks.

**Comment by bel2125** [comment]
Curious.
Windows adds a '\n' after a '\r' in some cases. Is the client and/or the server running on Windows?
Are you sure the file does not have this line endings - some Windows editors modify the line endings without even telling you?
Where did you take this screenshot? In the server? The client? On the wire?

**Comment by shawnye** [comment]
on windows
There is no exceeded '\n' in the file for uploading:
![hex0](https://cloud.githubusercontent.com/assets/579997/8712948/2921442e-2b95-11e5-9517-9b1517b2df91.jpg)

I am testing it on local machine, both the server and client are on the same computer.

ps: I am using `EmEditor` to show the pictures.

**Comment by shawnye** [comment]
the form:
<pre>
&lt;form action="clean_data.lua" id="form" method="post" accept-charset="utf-8" enctype="multipart/form-data"&gt;
    &lt;div&gt;
       &lt;table&gt;
        &lt;tbody&gt; 
	  &lt;tr&gt;
            &lt;td&gt;upload file：&lt;/td&gt;
            &lt;td&gt;&lt;input type="file" name="data_file" id="data_file" &gt;(*.csv)&lt;/td&gt;
          &lt;/tr&gt;	
          
           
        &lt;/tbody&gt;
      &lt;/table&gt;
    &lt;/div&gt;
    &lt;div style="text-align: center"&gt;
      &lt;input type="submit" name="" value="clean"   &gt;
      &lt;input type="button" name="" value="close"  &gt;
    &lt;/div&gt;
    &lt;/form&gt;
</pre>

**Comment by bel2125** [comment]
I have an idea why you might see this. Please test it whit the test/handle_form.lua which dumps the file content in hex:
https://github.com/bel2125/civetweb/commit/8dea7de0c4ca3cd39c920f73a713f4c310e6387e
It works for me on a Windows machine.

Probably your Lua script ("clean_data.lua") adds the extra "\r" (0D) when writing a "\n" (0A) to a file.

**Comment by bel2125** [comment]
Did you store the file in Lua?
Did you use `io.open(filename, "w")` or `io.open(filename, "wb")` or something else?
Please have a look at http://www.lua.org/pil/21.2.2.html !

**Comment by shawnye** [comment]
You got the point.
I write `io.open(filename, "w+")` ,cause the exceeded new line .

Thank you!

**Comment by bel2125** [comment]
So then let's close the issue.
