### ISSUE TITLE
Question regarding multi file uploads

### ISSUE THREAD

**Issue by wiseoldman95** [bel2125/civetweb#55]
I have modified the upload example and simply changed the form into this:
```
<form method="POST" action="/handle_post_request" enctype="multipart/form-data">
   <input name="file" type="file"> <br>
   <input name="file2" type="file"> <br>
   <input value="Upload" type="submit">
</form>
```

Next, I uploaded 2 files. Only one of them was saved on the server.
How do I handle multiple file uploads?

**Comment by bel2125** [comment]
There was a small bug, maybe due to a change in this code region I made some weeks ago.
I fixed it and modified the upload example accordingly.

**Comment by wiseoldman95** [comment]
Thanks, will test asap.

**Comment by wiseoldman95** [comment]
I confirm it works. Thanks for fixing this!
