### ISSUE TITLE
database written in same directory as civetweb was started from

### ISSUE THREAD

**Issue by Dialga** [bel2125/civetweb#56]
### Suppose the following shell session

$ ls ~/www
page.lp                 # this is the same file as test/page.lp
$ cd /tmp
$ civetweb -document_root ~/www/
Civetweb V1.6 started on port(s) 8080 with web root [/home/arch/www/]
      # Now go to http://127.0.0.1:8080/page.lp and reload the page a few times
^CExiting on signal 2, waiting for all threads to finish... done.
$ ls
requests.db
$ pwd
/tmp

### Expected results
requests.db to be written in ~/www, which was specified with -document_root

**Comment by bel2125** [comment]
I just tested it again and found no crash, and all requests stored in the database.
I used Ubuntu 14.10 to test and loaded the page more than 100 times.

Signal 2 is actually "SIGINT" (http://en.wikipedia.org/wiki/Unix_signal#POSIX_signals), which comes from pressing Ctrl-C at the terminal where you started civetweb.

I also closed civetweb with Ctrl-C, then I opened the requests.db in the sqlite3 shell (debian package sqlite3):
sqlite3 requests.db
.tables
select * from requests;

... and there were the >100 requests.

Can you explain in more detail what problem you found and what system you are using?

**Comment by bel2125** [comment]
Or did you mean everything worked, but you would like the data base to be stored in a different location?

**Comment by Dialga** [comment]
Yes everything worked, just that the database was written to the wrong directory, I was assuming databases get created in the directory passed to -document_root, not the the any random directory civetweb may have been started from, for example /tmp or / even.

**Comment by bel2125** [comment]
It seems the detailed explanation I wrote here some minutes ago is just gone, for whatever reason.

Short: This is an intended feature.
Use `mg.document_root .. "/request.db"` if you want to have it in the document_root - but I do not recommend that, you should not put a database into the *webroot* directory. Better use an explicitly defined *offroot* directory to store information that is not directly (static or dynamic) html content.

**Comment by bel2125** [comment]
# TODO
Reminder for activities to document the current behavior:
**1)** Add a comment to the example page (page.lp und page.lua)
**2)** Add a description how directories are meant to be used to the manual
**3)** Some explanation why this is useful and some best practices (basically recreate what is gone to digital nirvana some moments ago)

**Comment by bel2125** [comment]
As already stated above:
This is a feature, not a bug. Please either start the server in a proper directory, or use a proper path in the Lua script.
