### ISSUE TITLE
Crash when listening several ports

### ISSUE THREAD

**Issue by etrinh** [bel2125/civetweb#58]
Hi,

When I listen to several ports, for example: "443s, 80r", but port 80 is already used, civetweb crash during ssl_locking_callback due to an invalid mutex.

Best Regards,
Eric

**Comment by bel2125** [comment]
Your configuration is pretty much standard, and tested a thousand times - beside that I always used "80r,443s" but I tested now that the order makes no difference.

In fact for me, this configuration works perfectly on Win32 / Visual Studio. In Civetweb, there is the SO_REUSEADDR option set, so the civetweb also opens an already uses port.

Linux says in this case "set_port_options: Can not bind to port 80r: 98 (Port already in use)" and starting civetweb fails - but not with a crash.

So I can not reproduce this.
Could you specify exactly what system you are using? 
Which OS + Version?
Did you test a prebuild Civetweb binary from SourceForge?
Did you build it on your own? If so, which compiler, what defines? Can you reproduce the crash with a prebuilt binary?

**Comment by etrinh** [comment]
I use Windows 7 with own compiled civetweb with Mingw64 (gcc 4.8.0)

It seems that the crash happens after the free_context.
Effectively, civetweb returns with error during listening port binding.
The mutexes are destroyed during the free_context, but openssl seems to still try to acquire them. I don't really know the obscure internals of openssl, so I don't know why.
The port 80 is in my case used by another process (IIS), so the SO_REUSEADDR can't allow to reuse that port.

I have just tried to insert "uninitialize_ssl(ctx);" just before mutexes destruction in free_context. It seems to work. At least, it doesn't crash.

Thanks,
Eric

**Comment by etrinh** [comment]
For information, here is a patch I used. It allows to not reinit ssl mutexes when already initialized (I preinit SSL with Qt at startup due to behaviour of RAND_status on Windows (which may take several seconds when HEAP becomes big), it makes also civetweb crashing at the same place).

```
--- civetwebOri.c	Tue Jan 06 16:30:06 2015
+++ civetweb.c	Tue Jan 06 18:40:52 2015
@@ -603,6 +603,8 @@
   (* (void (*)(unsigned long (*)(void))) crypto_sw[2].ptr)
 #define ERR_get_error (* (unsigned long (*)(void)) crypto_sw[3].ptr)
 #define ERR_error_string (* (char * (*)(unsigned long,char *)) crypto_sw[4].ptr)
+#define CRYPTO_get_locking_callback \
+  (* (void * (*)(void)) crypto_sw[5].ptr)
 
 /* set_ssl_option() function updates this array.
    It loads SSL library dynamically and changes NULLs to the actual addresses
@@ -642,6 +644,7 @@
     {"CRYPTO_set_id_callback", NULL},
     {"ERR_get_error",  NULL},
     {"ERR_error_string", NULL},
+    {"CRYPTO_get_locking_callback", NULL},
     {NULL,    NULL}
 };
 #endif /* NO_SSL */
@@ -6643,7 +6646,7 @@
 #endif /* !_WIN32 */
 
 #if !defined(NO_SSL)
-static pthread_mutex_t *ssl_mutexes;
+static pthread_mutex_t *ssl_mutexes = NULL;
 
 static int sslize(struct mg_connection *conn, SSL_CTX *s, int (*func)(SSL *))
 {
@@ -6738,20 +6741,23 @@
 
     if (mg_atomic_inc(&cryptolib_users)>1) return 1;
 
-    /* Initialize locking callbacks, needed for thread safety.
-       http://www.openssl.org/support/faq.html#PROG1 */
-    size = sizeof(pthread_mutex_t) * CRYPTO_num_locks();
-    if ((ssl_mutexes = (pthread_mutex_t *) mg_malloc((size_t)size)) == NULL) {
-        mg_cry(fc(ctx), "%s: cannot allocate mutexes: %s", __func__, ssl_error());
-        return 0;
-    }
+    if (CRYPTO_get_locking_callback() == NULL)
+    {
+        /* Initialize locking callbacks, needed for thread safety.
+           http://www.openssl.org/support/faq.html#PROG1 */
+        size = sizeof(pthread_mutex_t) * CRYPTO_num_locks();
+        if ((ssl_mutexes = (pthread_mutex_t *) mg_malloc((size_t)size)) == NULL) {
+            mg_cry(fc(ctx), "%s: cannot allocate mutexes: %s", __func__, ssl_error());
+            return 0;
+        }
 
-    for (i = 0; i < CRYPTO_num_locks(); i++) {
-        pthread_mutex_init(&ssl_mutexes[i], NULL);
-    }
+        for (i = 0; i < CRYPTO_num_locks(); i++) {
+            pthread_mutex_init(&ssl_mutexes[i], NULL);
+        }
 
-    CRYPTO_set_locking_callback(&ssl_locking_callback);
-    CRYPTO_set_id_callback(&ssl_id_callback);
+        CRYPTO_set_locking_callback(&ssl_locking_callback);
+        CRYPTO_set_id_callback(&ssl_id_callback);
+    }
 
     return 1;
 }
@@ -6823,12 +6829,16 @@
     (void)ctx;
 
     if (mg_atomic_dec(&cryptolib_users)==0) {
-        CRYPTO_set_locking_callback(NULL);
-        for (i = 0; i < CRYPTO_num_locks(); i++) {
-            pthread_mutex_destroy(&ssl_mutexes[i]);
+        if (ssl_mutexes != NULL) {
+            CRYPTO_set_locking_callback(NULL);
+            for (i = 0; i < CRYPTO_num_locks(); i++) {
+                pthread_mutex_destroy(&ssl_mutexes[i]);
+            }
+            CRYPTO_set_locking_callback(NULL);
+            CRYPTO_set_id_callback(NULL);
+            mg_free(ssl_mutexes);
+            ssl_mutexes = NULL;
         }
-        CRYPTO_set_locking_callback(NULL);
-        CRYPTO_set_id_callback(NULL);
     }
 }
 #endif /* !NO_SSL */
@@ -7624,10 +7634,7 @@
     if (ctx->ssl_ctx != NULL) {
         SSL_CTX_free(ctx->ssl_ctx);
     }
-    if (ssl_mutexes != NULL) {
-        mg_free(ssl_mutexes);
-        ssl_mutexes = NULL;
-    }
+    uninitialize_ssl(ctx);
 #endif /* !NO_SSL */
 
     /* Deallocate worker thread ID array */
```

Eric

**Comment by bel2125** [comment]
> Edit: another information, maybe important: 
> I use civetweb inside a Qt application, with SSL already initialized... 

Yes, this is very important.
When you have SSL (libcrypto) already initialized, CivetWeb should neither initialize nor uninitialize it again. Initializing will change the locking callback and replace the one already set by Qt. While this probably does not cause an immediate problem it is at least undesired.

**Please try the following:**
There is a variable `cryptolib_users` that is a reference counter for initializing libcrypto:
https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L6724
Initialize with **cryptolib_users = 1** instead of 0, to tell civetweb there is another user of this lib.
If everything works as expected, this should be the only change required.
Please **test** this, and **tell me** if it works!

**Comment by etrinh** [comment]
Yes, this works! Thanks!
Would it be possible to have an API function to set this variable?
Thanks,
Eric

**Comment by bel2125** [comment]
I an not sure if an API function is the right way to do this.
It could be called only once, before the first call to mg_start. Then one could also explicitly add a function mg_initlib(int initSSL) and mg_exitlib() and do not do any reference counting in civetweb - but this would break compatibility.

As an alternative, I could add a compiler define. If this compiler define is set, then the variable is initialized to 1 instead of 0.

**Comment by etrinh** [comment]
Would be perfect!
Thanks

**Comment by wiseoldman95** [comment]
I also experience the crash without even needing 2 ports. Just run civetweb twice on 443s and the second instance crashes.

**Comment by bel2125** [comment]
In Linux I got "set_port_options: Can not bind to port 443s: 98 (Port already in use)" when I tried to start the second civetweb process. Please always specify which system you are using.

**Comment by wiseoldman95** [comment]
I was using a Linux system, however I don't recall whether it was Civetweb or Mognoose that caused the issue (And which version). Like I said, I need to double check the facts.

**Comment by bel2125** [comment]
@etrinh: the define SSL_ALREADY_INITIALIZED should work
@wiseoldman95: please check it again and tell me if you found any problem

**Comment by wiseoldman95** [comment]
This is still reproducible with the latest version of Civetweb. It has nothing to do with https.


```
#include <string.h>
#include <stdio.h>
#include "civetweb.h"
char * PORT="5555";


int helloWorld(struct mg_connection *conn, void *cbdata)
{
	struct mg_request_info * req_info = mg_get_request_info(conn);	
	 mg_printf(conn,
	"HTTP/1.1 200 OK\r\n"
	"Content-Type: text/plain\r\n"
	"Content-Length: 5\r\n"
	"\r\n"
	"hello");
	return 1;
}

int main(void)
{
	struct mg_context *ctx;
	struct mg_callbacks callbacks;
	const char *options[] = {"listening_ports", PORT, NULL};
	memset(&callbacks, 0, sizeof(callbacks));
	ctx = mg_start(&callbacks, NULL, options);
	printf("Server is running on port %s!\n",PORT);
	
	mg_set_request_handler(ctx,"/hello", helloWorld,0);
	getchar();
	mg_stop(ctx);
    return 0;
}
```

Now, compile using the following:
```
gcc -o server.out civetweb.c main.c -ldl -lpthread
```

Now, run it twice.

Instance 1 output:
```
Server is running on port 5555!
```

Instance 2 output:
```
Server is running on port 5555!
Segmentation fault

```

**Comment by etrinh** [comment]
I think your problem comes from a NULL ctx after the second instance.

**Comment by wiseoldman95** [comment]
Thanks! That resolved it.
```
int main(void)
{
	struct mg_context *ctx;
	struct mg_callbacks callbacks;
	const char *options[] = {"listening_ports", PORT, NULL};
	memset(&callbacks, 0, sizeof(callbacks));
	ctx = mg_start(&callbacks, NULL, options);
	if (ctx==NULL)
	{
		printf("Server FAILED to run on port %s!\n",PORT);
		return -1;
	}
	printf("Server is running on port %s!\n",PORT);
	
	mg_set_request_handler(ctx,"/hello", helloWorld,0);
	getchar();
	mg_stop(ctx);
    return 0;
}
```

**Comment by bel2125** [comment]
Do you think we can close this issue, or is there anything left unresolved, untested or unanswered?

**Comment by wiseoldman95** [comment]
Closing is fine by me. My issue was a misuse of the interface rather than a bug.
