### ISSUE TITLE
Bad 'if' check in handle_websocket_request

### ISSUE THREAD

**Issue by DoubtedEd** [bel2125/civetweb#63]
In handle_websocket_request you put the result of match_prefix in lua_websock, which returns -1 if false. You then check if lua_websock is true, shouldn't this instead check if lua_wesock is greater than 0?

For me this was causing a crash elsewhere in your code but I see you've fixed that crash already. Do you have an idea on when you'll release 1.7?

**Comment by bel2125** [comment]
I did not fix a date yet.
When all open issues are either fixed or postponed, and I had some time for testing. 
Building and testing for all platforms is the most time consuming part, especially for some platforms that I do not own and where I have no unlimited access but need others to do the tests.

**Comment by bel2125** [comment]
It took a while, but the next release is now ready:
https://github.com/bel2125/civetweb/releases/tag/v1.7
https://groups.google.com/forum/#!topic/civetweb/K2uDhP4PJ50
