### ISSUE TITLE
embedding in cpp

### ISSUE THREAD

**Issue by agauniyal** [bel2125/civetweb#64]
*This is not a bug or issue*
Hi , I'm starting out with c++ into web development for some pet projects. While reading embedding guide for civetweb , I was a bit confused about this procedure : 

1.Create CivetHandlers for each URI.
2.Register the handlers with CivertServer::addHandler()
3.CivetServer starts on contruction and stops on destruction.
4.Use contructor options to select the port and document root among other things.
5.Use constructor callbacks to add your own hooks.

I have programmed in c++ ( native , never web) and in LAMP stack too , but this approach is quiet new to me. What do these handlers stand for and what are URI? 
From my requirements , I need CiverServer to listen to ports continously , taking up any incoming connection , parsing out http headers ( might remove them completely or read them and react accordingly ) and lets say execute a function according to request data. 

Does URI stands for incoming connection? And I have no idea how it would handle multiple simultaneous connections ( 5 6 incoming connections ).
Thanks in advance :smile:

**Comment by bel2125** [comment]
For questions how to use the server, I would recommend the mailing list:
https://groups.google.com/forum/#!forum/civetweb

URI stands for Uniform Resource Identifier: http://en.wikipedia.org/wiki/Uniform_resource_identifier
Did you take a look at the examples: https://github.com/bel2125/civetweb/tree/master/examples
e.g.: embedded_c and embedded_cpp?

The number of connection is just a configuration parameter "num_threads" which is 50 by default. So up to 50 incoming connections are treated simultaneous, some additional connections can be queued. If you need more than that, you can increase this number - I tested more than 30000 simultaneous connections (on a 64 bit Linux machine with 8 GB RAM).

Do you want to have your handler functions in C, C++ in Lua or combined?

**Comment by agauniyal** [comment]
I am most comfortable with c++ so I guess everything would seem good in it ( handlers too) . And I get the URI part ( I knew about them but thought civetweb was using some other terminalogy ) , still I don't get the handler part. Are they like routes in other web stacks. For example , a get::route for http://mysite.com/ would handle all get request thrown at this url and would process them appt.

**Comment by bel2125** [comment]
http://en.wikipedia.org/wiki/Uniform_resource_identifier#URLs:
The URL http://example.org/wiki/Main_Page is split by the browser into a http request targeted at example.org, port 80, for the URI /wiki/Main_Page. If example.org would run a civetweb server, then the URI string would be /wiki/Main_page

Best would be you compile the "embedded_c" examples, and try to open http://localhost:8888/a,  http://localhost:8888/a/a, http://localhost:8888/a/b and http://localhost:8888/a/c
The handlers are set like this:
    mg_set_request_handler(ctx,"/a", AHandler,0);
    mg_set_request_handler(ctx,"/a/b", ABHandler,0);

**Comment by bel2125** [comment]
You can do the same with the C++ example (embedded_cpp) as well. It uses Port 8081 instead of 8888.

**Comment by bel2125** [comment]
I hope you got all the information you needed from the manual and the examples in the civetweb repository. If you missed something, please tell me, so I can improve the documentation.

Otherwise, I will close this request ("issue") in a few days.

**Comment by agauniyal** [comment]
Many users would be coming from traditional web stack ( Php-SQL) background , so a little refinement in terminology would help :smile: . Rest everything is good :+1:  and you can close the issue.

**Comment by bel2125** [comment]
"Issue" was a question which is now answered.
--> close
