### ISSUE TITLE
CGI POST is no longer working

### ISSUE THREAD

**Issue by sunsetbrew** [bel2125/civetweb#65]
Keep getting a 405 for method not supported.  Looks like a bunch of REST code when in and broke it.

**Comment by sunsetbrew** [comment]
I added POST to the options at line 6325 and it seemed to work.  I did not submit a patch because the comment above it looks to be leaving POST out on purpose 
    /* 13.3. everything but GET and HEAD (e.g. POST) */
I don't really understand why.

**Comment by bel2125** [comment]
I thought at this point (step 13) it should be certain that the resource is a normal file, e.g., something.html. Any you can not POST to something.html

Scripts should have been handled above:

    /* 10. File is handled by a script. */
    if (is_script_resource) {
        handle_file_based_request(conn, path, &file);
        return;
    }

Maybe there is a problem, that the CGI page is not recognized as a script.

**Comment by sunsetbrew** [comment]
By changing the line, the CGI is executed and the POST goes through fine.  All the CGI GET requests are working fine too.

**Comment by sunsetbrew** [comment]
I have been looking at it and the check in handle_file_based_request is much simpler than the check in interpret_uri.  If I had the guess, I would say that interpret_uri has broken for a long time.  Further, but totally off topic, SSI_EXTENSIONS are not being checked in interpret_uri. 

I have not found where the value of CGI_EXTENSION is being set.  I have not had to set that before as I my CGI scripts end with *.cgi.

**Comment by bel2125** [comment]
I think currently only sub-paths (x.cgi/abc) of cgi scripts are identified as `is_script_resource`, while the script itself (x.cgi) is not. Script resources can handle everything: GET, POST, PUT, DELETE, ...
Non-script resources are files that will be replaced by PUT, deleted by DELETE, etc.

**Comment by sunsetbrew** [comment]
Yes, i think that is the problem as well.  So it is a bug in interpret_uri

**Comment by bel2125** [comment]
SSI is not a script resource, so SSI_EXTENSIONS don't need to be checked. SSI only handles GET, not POST.

The CGI extensions did not change recently: https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L720

I rewrote the original handle_request, because it was unnecessary complicated, but I did not rewrite interpret_uri yet. Just changing interpret_uri in a way that CGI files are script_resources themselves, would change the way PUT works for CGI files. I currently x.cgi/ is a script resouce but x.cgi is the script itself. If x.cgi is a script resource, then POST will work like before, but PUT will be sent to the script instead of replacing the script file.

**Comment by bel2125** [comment]
I think this is the behavior of the last release (v1.6). 
Do you think it is the correct one?

GET xy.cgi calls xy.cgi and returns the page generated by the script
POST xy.cgi calls xy.cgi and returns the page generated by the script
PUT xy.cgi replaces xy.cgi by the new content
DELETE cx.cgi removes xy.cgi
GET xy.cgi/* calls xy.cgi and returns the page generated by the script
POST xy.cgi/* calls xy.cgi and returns the page generated by the script
PUT xy.cgi/* calls xy.cgi and returns the page generated by the script
DELETE xy.cgi/* calls xy.cgi and returns the page generated by the script

**Comment by bel2125** [comment]
> I think this is the behavior of the last release (v1.6). 
... it seems it was never really correct yet. 
So we should just make it correct, comprehensible and logical now.

**Comment by sunsetbrew** [comment]
I agree with your analysis.  I am surprised it was not realized earlier.
The code you change looks a lot better than before.

**Comment by bel2125** [comment]
I think this is fixed since months, and we just forgot to close it.
