### ISSUE TITLE
Question: how to get header, parse POSTed content in Lua?

### ISSUE THREAD

**Issue by shawnye** [bel2125/civetweb#70]
I found `mg_get_header()` in `civetweb.h`, but no counterpart in lua mg(table)

and I can not find function that can easily parse POSTed content in lua, could you add it or give me aa direction about how to deal it?

 Thank you.

**Comment by shawnye** [comment]
I know how to do it if no file upload:
parse POSTed content :  `mg.get_var(mg.read(), 'var_name')`
***but when post with `enctype="multipart/form-data"`, it seems failed.***

get header:  
<pre>
local headers = mg.request_info.http_headers
    for k,v in pairs(headers) do
      mg.write(k .. '=' .. v .. "<br/>")
    end
</pre>

**Comment by bel2125** [comment]
> sadlly , I can not use `mg.get_header('header_name')` do C++ers do

`mg.request_info.http_headers['header_name']` works in Lua

**Comment by shawnye** [comment]
Thank you very much, bel2125 !


 How can I get field value and uploaded file when posted with enctype="multipart/form-data" ?

I try `mg.get_var(mg.read(), 'var_name')`, it seems to fail.

**Comment by bel2125** [comment]
"multipart/form-data" is not supported by mg.get_var, just the default
encoding "application/x-www-form-urlencoded" (see
http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1)

**Comment by bel2125** [comment]
"multipart/form-data" is not supported by mg.get_var, just the default
encoding "application/x-www-form-urlencoded" (see
http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1)

formdata has to be read directly, without using get_var

**Comment by shawnye** [comment]
I see, thank you.

Will civetweb support file upload in the near future?

**Comment by bel2125** [comment]
It already does - for C there is the upload function, for Lua you can do it directly with mg.read
The C example is here: https://github.com/bel2125/civetweb/blob/master/examples/upload/upload.c
I can add a Lua example

**Comment by bel2125** [comment]
see also https://groups.google.com/forum/#!topic/civetweb/m9ojynOyzU4

**Comment by bel2125** [comment]
I added an example how to do this in Lua.
Please have a look:
https://github.com/bel2125/civetweb/blob/master/test/form.html
https://github.com/bel2125/civetweb/blob/master/test/handle_form.lua

There is also some discussion in the Civetweb forum:
https://groups.google.com/forum/#!topic/civetweb/m9ojynOyzU4

**Comment by bel2125** [comment]
If there are no further questions or comments, I will close this issue in a few days.
I think the examples/tests I added could be a good starting point for a specific form handler.

**Comment by bel2125** [comment]
A working example is available now.
For further details see the discussion forum.
