### ISSUE TITLE
Issues when compiling with TDM-GCC

### ISSUE THREAD

**Issue by Dialga** [bel2125/civetweb#78]
I'm getting a plethora of errors when attempting to compile with TDM-GCC on Windows.
Is building with MinGW/TDM-GCC still supported?

**Comment by Dialga** [comment]
Here's the make log

$ CC=gcc mingw32-make build WITH_LUA=1 WITH_WEBSOCKET=1
Lua: using static library
Makefile:249: target 'out/src/third_party' given more than once in the same rule
.
Makefile:249: target 'out/src/third_party' given more than once in the same rule
.
gcc -c -W -Wall -O2 -DWIN32 -Iinclude  -DUSE_STACK_SIZE=102400 -std=gnu11 -DNDEB
UG -Isrc/third_party/lua-5.2.3/src -DLUA_COMPAT_ALL -DUSE_LUA -Isrc/third_party
-DTHREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -Isrc/third
_party -DUSE_LUA_SQLITE3 -DUSE_LUA_FILE_SYSTEM -DUSE_LUA_LUAXML -DUSE_WEBSOCKET
-DUSE_TIMERS src/civetweb.c -o out/src/civetweb.o
src/civetweb.c:150:0: warning: "W_OK" redefined
 #define W_OK (2) /* http://msdn.microsoft.com/en-us/library/1w06ktdy.aspx */
 ^
In file included from c:/TDM-GCC-32/include/fcntl.h:20:0,
                 from src/civetweb.c:79:
c:/TDM-GCC-32/include/io.h:326:0: note: this is the location of the previous def
inition
 #define W_OK 2 /* Check for write permission */
 ^
src/civetweb.c:186:0: warning: "USE_TIMERS" redefined
 #define USE_TIMERS
 ^
:0:0: note: this is the location of the previous definition
src/civetweb.c:238:0: warning: "INT64_MAX" redefined
 #define INT64_MAX  9223372036854775807
 ^
In file included from c:/TDM-GCC-32/lib/gcc/mingw32/4.9.2/include/stdint.h:9:0,
                 from c:/TDM-GCC-32/include/process.h:18,
                 from src/civetweb.c:111:
c:/TDM-GCC-32/include/stdint.h:95:0: note: this is the location of the previous
definition
 #define INT64_MAX 9223372036854775807LL
 ^
src/civetweb.c: In function 'mg_atomic_inc':
src/civetweb.c:873:32: warning: passing argument 1 of 'InterlockedIncrement' fro
m incompatible pointer type
     ret = InterlockedIncrement((volatile unsigned int *) addr);
                                ^
In file included from c:/TDM-GCC-32/include/windows.h:50:0,
                 from src/civetweb.c:97:
c:/TDM-GCC-32/include/winbase.h:1857:13: note: expected 'volatile LONG *' but ar
gument is of type 'volatile unsigned int *'
 LONG WINAPI InterlockedIncrement(LONG volatile *);
             ^
src/civetweb.c: In function 'mg_atomic_dec':
src/civetweb.c:886:32: warning: passing argument 1 of 'InterlockedDecrement' fro
m incompatible pointer type
     ret = InterlockedDecrement((volatile unsigned int *) addr);
                                ^
In file included from c:/TDM-GCC-32/include/windows.h:50:0,
                 from src/civetweb.c:97:
c:/TDM-GCC-32/include/winbase.h:1848:13: note: expected 'volatile LONG *' but ar
gument is of type 'volatile unsigned int *'
 LONG WINAPI InterlockedDecrement(LONG volatile *);
             ^
src/civetweb.c: In function 'mg_join_thread':
src/civetweb.c:2119:13: warning: variable 'err' set but not used [-Wunused-but-s
et-variable]
         int err;
             ^
src/civetweb.c: In function 'mg_send_file2':
src/civetweb.c:4194:70: warning: unused parameter 'timeout' [-Wunused-parameter]

 void mg_send_file2(struct mg_connection *conn, const char *path, int timeout)
                                                                      ^
In file included from src/civetweb.c:5335:0:
src/mod_lua.inl: In function 'mmap':
src/mod_lua.inl:6:25: warning: unused parameter 'addr' [-Wunused-parameter]
 static void *mmap(void *addr, int64_t len, int prot, int flags, int fd,
                         ^
src/mod_lua.inl:6:48: warning: unused parameter 'prot' [-Wunused-parameter]
 static void *mmap(void *addr, int64_t len, int prot, int flags, int fd,
                                                ^
src/mod_lua.inl:6:58: warning: unused parameter 'flags' [-Wunused-parameter]
 static void *mmap(void *addr, int64_t len, int prot, int flags, int fd,
                                                          ^
src/mod_lua.inl:7:9: warning: unused parameter 'offset' [-Wunused-parameter]
     int offset)
         ^
src/mod_lua.inl: In function 'munmap':
src/mod_lua.inl:16:40: warning: unused parameter 'length' [-Wunused-parameter]
 static void munmap(void *addr, int64_t length)
                                        ^
In file included from src/civetweb.c:5335:0:
src/mod_lua.inl: In function 'lua_websocket_close':
src/mod_lua.inl:1379:43: warning: unused variable 'shared_websock_list' [-Wunuse
d-variable]
     struct mg_shared_lua_websocket_list **shared_websock_list = &(conn->ctx->sh
ared_lua_websockets);
                                           ^
src/civetweb.c: In function 'handle_websocket_request':
src/civetweb.c:5750:88: warning: unused parameter 'is_script_resource' [-Wunused
-parameter]
 static void handle_websocket_request(struct mg_connection *conn, const char *pa
th, int is_script_resource)

        ^
src/civetweb.c: In function 'mg_upload2':
src/civetweb.c:5868:77: warning: unused parameter 'timeout' [-Wunused-parameter]

 int mg_upload2(struct mg_connection *conn, const char *destination_dir, int tim
eout)
                                                                             ^
src/civetweb.c: In function 'set_ports_option':
src/civetweb.c:6543:20: warning: format '%d' expects argument of type 'int', but
 argument 6 has type 'DWORD' [-Wformat=]
                    (int) vec.len, vec.ptr, ERRNO, strerror(errno));
                    ^
src/civetweb.c: In function 'getreq':
src/civetweb.c:7123:13: warning: implicit declaration of function '_strtoi64' [-
Wimplicit-function-declaration]
             conn->content_len = strtoll(cl, &endptr, 10);
             ^
src/civetweb.c: In function 'free_context':
src/civetweb.c:7694:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(suppress: 6001)
 ^
src/civetweb.c: In function 'get_system_name':
src/civetweb.c:7767:5: warning: format '%d' expects argument of type 'int', but
argument 3 has type 'DWORD' [-Wformat=]
     sprintf(name, "Windows %d.%d", dwMajorVersion, dwMinorVersion);
     ^
src/civetweb.c:7767:5: warning: format '%d' expects argument of type 'int', but
argument 4 has type 'DWORD' [-Wformat=]
src/civetweb.c:7759:11: warning: variable 'dwBuild' set but not used [-Wunused-b
ut-set-variable]
     DWORD dwBuild = 0;
           ^
src/civetweb.c: In function 'mg_start':
src/civetweb.c:7793:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(suppress: 28125)
 ^
src/civetweb.c: At top level:
src/civetweb.c:1669:12: warning: 'pthread_mutex_trylock' defined but not used [-
Wunused-function]
 static int pthread_mutex_trylock(pthread_mutex_t *mutex)
            ^
gcc -c -W -Wall -O2 -DWIN32 -Iinclude  -DUSE_STACK_SIZE=102400 -std=gnu11 -DNDEB
UG -Isrc/third_party/lua-5.2.3/src -DLUA_COMPAT_ALL -DUSE_LUA -Isrc/third_party
-DTHREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -Isrc/third
_party -DUSE_LUA_SQLITE3 -DUSE_LUA_FILE_SYSTEM -DUSE_LUA_LUAXML -DUSE_WEBSOCKET
-DUSE_TIMERS src/main.c -o out/src/main.o
src/main.c: In function 'verify_existence':
src/main.c:505:9: warning: variable 'len' set but not used [-Wunused-but-set-var
iable]
     int len;
         ^
src/main.c: In function 'set_absolute_path':
src/main.c:541:13: warning: implicit declaration of function '_getcwd' [-Wimplic
it-function-declaration]
             IGNORE_UNUSED_RESULT(getcwd(path, sizeof(path)));
             ^
In file included from src/../src/third_party/lua-5.2.3/src/lua.c:50:0,
                 from src/main.c:563:
c:/TDM-GCC-32/include/io.h: At top level:
c:/TDM-GCC-32/include/io.h:251:39: error: conflicting types for '_getcwd'
 _CRTIMP char* __cdecl __MINGW_NOTHROW _getcwd (char*, int);
                                       ^
src/main.c:52:21: note: previous implicit declaration of '_getcwd' was here
 #define getcwd(a,b) _getcwd(a,b)
                     ^
src/main.c:30:41: note: in definition of macro 'IGNORE_UNUSED_RESULT'
 #define IGNORE_UNUSED_RESULT(a) (void)((a) && 1)
                                         ^
src/main.c:541:34: note: in expansion of macro 'getcwd'
             IGNORE_UNUSED_RESULT(getcwd(path, sizeof(path)));
                                  ^
src/main.c: In function 'SettingsDlgProc':
src/main.c:746:81: warning: unused parameter 'lP' [-Wunused-parameter]
 static BOOL CALLBACK SettingsDlgProc(HWND hDlg, UINT msg, WPARAM wParam, LPARAM
 lP)

 ^
src/main.c: In function 'get_password':
src/main.c:965:10: warning: unused variable 'hDlg' [-Wunused-variable]
     HWND hDlg = NULL;
          ^
src/main.c: In function 'WindowProc':
src/main.c:1411:5: warning: missing braces around initializer [-Wmissing-braces]

     static SERVICE_TABLE_ENTRY service_table[2] = {0};
     ^
src/main.c:1411:5: warning: (near initialization for 'service_table[0]') [-Wmiss
ing-braces]
src/main.c: In function 'MakeConsole':
src/main.c:1508:5: warning: implicit declaration of function 'GetConsoleWindow'
[-Wimplicit-function-declaration]
     int ok = (GetConsoleWindow() != NULL);
     ^
src/main.c:1508:34: warning: comparison between pointer and integer
     int ok = (GetConsoleWindow() != NULL);
                                  ^
src/main.c:1510:9: warning: implicit declaration of function 'AttachConsole' [-W
implicit-function-declaration]
         if (!AttachConsole(ATTACH_PARENT_PROCESS)) {
         ^
src/main.c:1510:28: error: 'ATTACH_PARENT_PROCESS' undeclared (first use in this
 function)
         if (!AttachConsole(ATTACH_PARENT_PROCESS)) {
                            ^
src/main.c:1510:28: note: each undeclared identifier is reported only once for e
ach function it appears in
src/main.c:1521:34: warning: comparison between pointer and integer
         ok = (GetConsoleWindow() != NULL);
                                  ^
src/main.c: In function 'WinMain':
src/main.c:1542:30: warning: passing argument 2 of 'init_server_name' from incom
patible pointer type
     init_server_name(__argc, __argv);
                              ^
src/main.c:455:13: note: expected 'const char **' but argument is of type 'char
**'
 static void init_server_name(int argc, const char *argv[])
             ^
src/main.c:1536:30: warning: unused parameter 'hInst' [-Wunused-parameter]
 int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR cmdline, int show)
                              ^
src/main.c:1536:47: warning: unused parameter 'hPrev' [-Wunused-parameter]
 int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR cmdline, int show)
                                               ^
src/main.c:1536:60: warning: unused parameter 'cmdline' [-Wunused-parameter]
 int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR cmdline, int show)
                                                            ^
src/main.c:1536:73: warning: unused parameter 'show' [-Wunused-parameter]
 int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR cmdline, int show)
                                                                         ^
src/main.c: At top level:
src/main.c:209:13: warning: 'create_config_file' defined but not used [-Wunused-
function]
 static void create_config_file(const char *path)
             ^
Makefile:256: recipe for target 'out/src/main.o' failed
mingw32-make: *** [out/src/main.o] Error 1

**Comment by bel2125** [comment]
I'm not intentionally not supporting MinGW - I have not tested MinGW, because I failed twice to set up a proper build environment for MinGW, although I tried several hours each time. I had the same problem when trying to reproduce issue 57 (https://github.com/bel2125/civetweb/issues/57). I could only build with MinGW by calling the compiler directly, like this, without error: gcc src\civetweb.c src\main.c -Iinclude\ -lws2_32 -lpthread -lcomdlg32 - I did not manage to get "make" running. For Windows, I usually build with Visual Studio, and with gcc for Linux (using "make").
Probably MinGW uses a different "make" than Linux - BSD also uses a different "make".

If someone knows how to get make working for MinGW, please tell me.

The other problem is, MinGW apparently uses other headers (Windows system SDK) as Microsoft. This was also the problem for issue 57. It also seems that different MinGW versions use different Windows SDKs - in my MinGW, ATTACH_PARENT_PROCESS is defined, so I can compile and run the server without error (from the command line). Also the functions starting with underscore (_strtoi64, _getcwd, ...) seem to be in different headers, or have no underscores or whatever the difference between the Microsoft Windows SDK and the MinGW Windows SDK might be here. The problem is the same for all functions that raise "implicit declaration" warnings, and for the different parameter type definitions (e.g., InterlockedIncrement).

I guess, these different SDKs must lead to warnings. I don't know how to avoid this without adding dozens of #ifdef, and I don't know how to check for the different SDKs in MinGW.

ATTACH_PARENT_PROCESS is defined in WinCon.h:
#define ATTACH_PARENT_PROCESS ((DWORD)-1)
I could and an 
#ifndef ATTACH_PARENT_PROCESS 
#define ATTACH_PARENT_PROCESS ((DWORD)-1)
#endif
if this is the only error with MinGW

Any suggestions how the MinGW problem can be thoroughly soled?

**Comment by Dialga** [comment]
I have finally managed to successfully build using MinGW #80.
I have tested it with MinGW-w64 and TDM-GCC on Windows 7 32bit. I haven't tested it using the original MinGW, but it should build fine with it too.

After looking through the MinGW headers, it seems that [ATTACH_PARENT_PROCESS and AttachConsole](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681952%28v=vs.85%29.aspx) only work if you define [_WIN32_WINNT](https://msdn.microsoft.com/en-us/library/6sehtctf.aspx) as >= 0x501.

For _getcwd to work, the header io.h needed to be included, after a quick search I found the header was included but in the wrong place, thus I moved it closer to the top.

I've also added from the deprecated Makefile the command to build the icon into the executable, when using MinGW.

As shown above, most of the warnings can be hidden if -Wall is removed from CFLAGS.

For the main warnings that persist when building without -Wall, I'll post below for you see.

**Comment by Dialga** [comment]
make build CC=gcc WITH_LUA=1 WITH_WEBSOCKET=1
Lua: using static library
Makefile:259: target 'out/src/third_party' given more than once in the same rule.
Makefile:259: target 'out/src/third_party' given more than once in the same rule.
gcc -c -W -O2 -DWIN32 -Iinclude  -DUSE_STACK_SIZE=102400 -DNDEBUG src/civetweb.c -o out/src/civetweb.o
src/civetweb.c:150:0: warning: "W_OK" redefined
 #define W_OK (2) /* http://msdn.microsoft.com/en-us/library/1w06ktdy.aspx */
 ^
In file included from C:/TDM-GCC-32/include/fcntl.h:20:0,
                 from src/civetweb.c:79:
C:/TDM-GCC-32/include/io.h:326:0: note: this is the location of the previous definition
 #define W_OK 2 /* Check for write permission */
 ^
src/civetweb.c:238:0: warning: "INT64_MAX" redefined
 #define INT64_MAX  9223372036854775807
 ^
In file included from C:/TDM-GCC-32/lib/gcc/mingw32/4.9.2/include/stdint.h:9:0,
                 from C:/TDM-GCC-32/include/process.h:18,
                 from src/civetweb.c:111:
C:/TDM-GCC-32/include/stdint.h:95:0: note: this is the location of the previous definition
 #define INT64_MAX 9223372036854775807LL
 ^
src/civetweb.c: In function 'mg_atomic_inc':
src/civetweb.c:873:32: warning: passing argument 1 of 'InterlockedIncrement' from incompatible point
er type
     ret = InterlockedIncrement((volatile unsigned int *) addr);
                                ^
In file included from C:/TDM-GCC-32/include/windows.h:50:0,
                 from src/civetweb.c:97:
C:/TDM-GCC-32/include/winbase.h:1857:13: note: expected 'volatile LONG *' but argument is of type 'volatile unsigned int *'
 LONG WINAPI InterlockedIncrement(LONG volatile *);
             ^
src/civetweb.c: In function 'mg_atomic_dec':
src/civetweb.c:886:32: warning: passing argument 1 of 'InterlockedDecrement' from incompatible point
er type
     ret = InterlockedDecrement((volatile unsigned int *) addr);
                                ^
In file included from C:/TDM-GCC-32/include/windows.h:50:0,
                 from src/civetweb.c:97:
C:/TDM-GCC-32/include/winbase.h:1848:13: note: expected 'volatile LONG *' but argument is of type 'volatile unsigned int *'
 LONG WINAPI InterlockedDecrement(LONG volatile *);
             ^
gcc -c -W -O2 -DWIN32 -Iinclude  -DUSE_STACK_SIZE=102400 -DNDEBUG src/main.c -o out/src/main.o
src/main.c: In function 'WinMain':
src/main.c:1537:30: warning: passing argument 2 of 'init_server_name' from incompatible pointer type

     init_server_name(__argc, __argv);
                              ^
src/main.c:453:13: note: expected 'const char **' but argument is of type 'char **'
 static void init_server_name(int argc, const char *argv[])
             ^
