### ISSUE TITLE
Percent-encoding problems

### ISSUE THREAD

**Issue by xtne6f** [bel2125/civetweb#79]
I think `return -1;` of mg_url_encode() must be `break;`, or check 
the returned value. It causes buffer overrun.
Then, the encoded char's of print_dir_entry() and print_dav_dir_entry() should be three times(worst-case) the size. This is important to non-English environments.

**Comment by bel2125** [comment]
Yes, this must be a break.
This function truncates the string if the output buffer is not large enough, also if all input characters are "isalnum", so the return must be a break.
Thank you, I will fix this.

**Comment by bel2125** [comment]
return -1 changed to break
