### ISSUE TITLE
mg_read variable shadowing

### ISSUE THREAD

**Issue by kainjow** [bel2125/civetweb#98]
`mg_read` has a function param of `void* buf`, but also declares a local variable  `char buf[64]`.

This should be fixed as it generates a warning with `-Wshadow` on clang. I can look at it later but figured I'd give you a heads up.

**Comment by bel2125** [comment]
This is maybe also a merge error from pull request  #95.
I will ask the original author.

**Comment by keithel** [comment]
Aha, this is a bug I introduced..
I have a handle on how to fix and get back to you.

**Comment by keithel** [comment]
Adding -Wshadow on clang in Makefile would be nice too - so we can catch these easier.

**Comment by bel2125** [comment]
> Adding -Wshadow on clang in Makefile would be nice too
In #94, we planned to use cmake to generate the Makefile.
Probably this option can be added there, so it will be available for clang and gcc (if I understood cmake correctly).

**Comment by keithel** [comment]
There's more wrong with #95 ... T_T .. I'm working through it.

**Comment by bel2125** [comment]
Do you actually have a test client for this?
Otherwise I could add it to my old testclient (https://github.com/bel2125/civetweb/blob/master/testutils/testclient/testclient.c) which unfortunately currently only works for Windows.

**Comment by keithel** [comment]
I have some test code, but it's not specific to civetweb.. some unit tests that operate under Mac would be nice -- I'll have a look at testclient.c, see if I can get it compiling for Mac.

**Comment by bel2125** [comment]
testclient.c WinSocket code, and it does not yet use chunked transfer encoding.
It might be easier if I first make it work on Windows and Linux, and add a test for chunked encoding.
It's probably easier for you to move it from Linux to Mac OS (I don't have a Mac, so I can not do the conversion to Mac directly) - as you like.

**Comment by keithel** [comment]
Indeed, would be easier to move from Linux to Mac - it likely would involve hardly any changes :)

**Comment by bel2125** [comment]
I made a quick and dirty pared-down version of the testclient to check chunked transfer encoding for Linux: testutils/testclient_chunked_linux/testclient.c
See https://github.com/bel2125/civetweb/commit/da5c8d66836d377d789e3f1a57ed4db273ae5b9c

**Comment by bel2125** [comment]
@keithel: How should we proceed with this problem?
Will you have a look at it? Is the testclient of any use for you?
Can I assist in any way?

**Comment by keithel** [comment]
I'll have a chance to look at it tonight - I haven't looked at your test suite yet.
The code should be straightforward if you feel like looking at it.. If you want things working though - might want to revert my patches till it's all working.

**Comment by bel2125** [comment]
No, I dont want to revert the patch, I just added a TODO remark.
If you habe the code already working somewhere, it is better you habe a
look.
The idea in the code is clear, so I might habe a look during the weekend.


Am Dienstag, 21. April 2015 schrieb Keith Kyzivat :

**Comment by mattyclarkson** [comment]
Just bumped into this. I just renamed the variable but looks like there are better fixes in the works.

**Comment by bel2125** [comment]
Renaming it here (https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L2664) is probably not all that needs to be done, because in the following lines (the scope of the variable) there are a lot of operations with "buf", some only make sense with the function argument, others only with the local variable.
Renaming it will remove the "shadows ..." warning, but the program will probably crash or at least not work correctly.
A real fix of the logic is required here.

**Comment by mattyclarkson** [comment]
@bel2125, sorry, that comment was a bit rushed! I didn't mean to imply that renaming the variable was the correct solution, I didn't spend the time to understand the function. I was trying to get rid of the warning for the CMake build to work which has extremely strict warnings enabled. I mainly wanted to comment to I get notifications when a fix is found.

**Comment by kainjow** [comment]
@mattyclarkson you can use the Subscribe button to the right under Notifications without having to comment.

**Comment by bel2125** [comment]
I tried to fix chunked transfer encoding, and it seems to work at first sight.
I commented out the code that probably does not merge correctly (#95) and replaced it by something that could work, also it's not intensively tested yet:
https://github.com/bel2125/civetweb/commit/199afb7369a6a21ec347f6ccf35078f15adeb1bb

I would not call it ready for production code before some more intense tests - probably I did not consider something important.

**Comment by mattyclarkson** [comment]
@kainjow, ack should have looked for that. thanks!

**Comment by keithel** [comment]
I will test tomorrow - sorry, this week has been busy.

**Comment by bel2125** [comment]
> I will test tomorrow - sorry, this week has been busy.

No problem.
Meanwhile I tried to fix it on my own, and with the adapted testclient it seems to work.
The testclient (https://github.com/bel2125/civetweb/blob/master/testutils/testclient_chunked_linux/testclient.c) now also works for Windows (although there is still a "linux" in the directory path - I will rename this later). I am not sure if I considered every aspect.
Probably `discard_unread_request_data` needs some more attention (https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L2585), but I can take care of that.

I don't want to only use my *testclient_chunked* for testing. How did you test chunked transfer encoding?

**Comment by keithel** [comment]
Just looked over your changes. Your rework is nice! Better than the original imho.  Much more readable - having the tri-state is_chunked status is nice.

We didn't have any explicit test suite code - we were using a server we wrote to test this - it's essentially a data agnostic sync engine... I'll see if I can write or find a good chunked encoding unit test and adapt it for civetweb, add it to the codebase.

Before I do that though, at very least I'll test it in our server.

**Comment by keithel** [comment]
Server tests are giving me exceptions.. which was what I was getting after fixing the minor issues with the chunking code ported to Civetweb... Might be other logic since last MIT licensed Mongoose release causing issues... not sure what yet though.

**Comment by bel2125** [comment]
Are you using the civetweb source core, or do you have your own source based on the last MIT licensed mongoose code? The last MIT mongoose code was in summer 2013, and there are a lot of improvements in civetweb since that time. I also made some restructuring for some of the core methods, so if your original patch (pull request #95) is based on an old MIT fork, the differences might already be too large for a simple merge (as we can see).

You have the server code embedded in some closed source 1C application?

**Comment by keithel** [comment]
Our production code is running the old 2013 MIT mongoose code -- I've been testing by transplanting it with the Civetweb code + chunked encoding.

The original patch was indeed made by me taking the changes we made to the 2013 MIT Mongoose code and transplanting them to civetweb as of the time of pull request 95.

And yes - server code is embedded in a closed-source C++ application, with it's own unit tests.

**Comment by bel2125** [comment]
I recently rewrote the handle_request method and rewrote the Lua integration in the last version (https://github.com/bel2125/civetweb/blob/master/RELEASE_NOTES.md), so the logic is in some places a little different. But it should be compatible for all (typical) applications.
Are you currently trying to update to the current civetweb version?
Are you getting exceptions within civetweb?

**Comment by keithel** [comment]
Yes, trying to update to the current civetweb version, - no exceptions aren't directly in Civetweb code (or at least not exhibiting themselves there).

Sorry for the short reply.  Still trying to come up with some time to work on this.

**Comment by bel2125** [comment]
Ok. 
Let's complete testing the current implementation of chunked encoding here.
So, when you update to the current civetweb version, then you will have a working chunked encoding here.

**Comment by bel2125** [comment]
I think this works now, so let's close the issue.
